# ====== CONFIG ======
API_KEY = os.getenv("API_KEY")
API_SECRET = os.getenv("API_SECRET")
SUPABASE_DSN = os.getenv("SUPABASE_DSN")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")