name: Deploy Flask App

on:
  push:
    branches: [ "main" ]   # triggers when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run app with secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          PORT: ${{ secrets.PORT }}
          TRADINGSYMBOL: ${{ secrets.TRADINGSYMBOL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SUPABASE_DSN: ${{ secrets.SUPABASE_DSN }}
          SILVERMIC_TRADINGSYMBOL: ${{ secrets.SILVERMIC_TRADINGSYMBOL }}
        run: |
          source venv/bin/activate
          gunicorn -w 2 -b 0.0.0.0:$PORT main:app
