name: Deploy Flask App

on:
  push:
    branches: [ "main" ]   # triggers when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (test build)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Google Cloud VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          envs: API_KEY,API_SECRET,PORT,TRADINGSYMBOL,TELEGRAM_BOT_TOKEN,TELEGRAM_CHAT_ID,SUPABASE_DSN,SILVERMIC_TRADINGSYMBOL
          script: |
            cd ~/mft_ctt_alert
            git pull origin main
            source venv/bin/activate || python -m venv venv && source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            nohup gunicorn -w 2 -b 0.0.0.0:$PORT main:app &
